{% set name = "pyre-extensions" %}
{% set version = "0.0.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyre-extensions-{{ version }}.tar.gz
  sha256: 9554134f630d5918697786d0e1bbba243114b3d20d9bac60d3382763873e72c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - typing_inspect
    - typing-extensions

test:
  imports:
    - pyre_extensions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pyre-check.org
  summary: Type system extensions for use with the pyre type checker
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
